/**
 * Migration Map Markdown Renderer
 *
 * Renders the migration map as a human-readable markdown document.
 */

import type { MigrationMap, EntityMapping, FieldMapping, RelationMapping, EnumMapping } from './map';

/**
 * String labels for the markdown document
 */
export interface MapMarkdownStrings {
  title: string;
  generatedAt: string;
  target: string;
  entities: string;
  fields: string;
  relations: string;
  enums: string;
  notes: string;
  required: string;
  optional: string;
}

/**
 * Default English strings
 */
const DEFAULT_STRINGS: MapMarkdownStrings = {
  title: 'Migration Map',
  generatedAt: 'Generated At',
  target: 'Target',
  entities: 'Entities',
  fields: 'Fields',
  relations: 'Relations',
  enums: 'Enums',
  notes: 'Notes',
  required: 'Required',
  optional: 'Optional',
};

/**
 * Render migration map as markdown
 */
export function renderMigrationMapMd(
  map: MigrationMap,
  strings: Partial<MapMarkdownStrings> = {}
): string {
  const s = { ...DEFAULT_STRINGS, ...strings };
  const lines: string[] = [];

  // Header
  lines.push(`# ${s.title}`);
  lines.push('');
  lines.push(`**${s.generatedAt}:** ${map.generatedAt}`);
  lines.push('');
  lines.push(`**${s.target}:** ${map.target}`);
  lines.push('');

  // Entities
  lines.push(`## ${s.entities}`);
  lines.push('');

  for (const entity of map.entities) {
    lines.push(`### ${entity.name}`);
    lines.push('');
    lines.push(entity.description);
    lines.push('');
    lines.push(`**Primary Key:** \`${entity.primaryKey}\``);
    lines.push('');

    // Fields table
    lines.push(`#### ${s.fields}`);
    lines.push('');
    lines.push('| From | To | Type | Required | Notes |');
    lines.push('|------|-----|------|----------|-------|');

    for (const field of entity.fields) {
      const req = field.required ? 'Yes' : 'No';
      const notes = field.notes || '-';
      lines.push(`| \`${field.from}\` | \`${field.to}\` | \`${field.type}\` | ${req} | ${notes} |`);
    }
    lines.push('');

    // Relations
    if (entity.relations && entity.relations.length > 0) {
      lines.push(`#### ${s.relations}`);
      lines.push('');
      lines.push('| Type | From | To | Notes |');
      lines.push('|------|------|-----|-------|');

      for (const rel of entity.relations) {
        const notes = rel.notes || '-';
        lines.push(`| ${rel.type} | ${rel.from} | ${rel.to} | ${notes} |`);
      }
      lines.push('');
    }

    // Enums
    if (entity.enums && entity.enums.length > 0) {
      lines.push(`#### ${s.enums}`);
      lines.push('');

      for (const enumDef of entity.enums) {
        lines.push(`**${enumDef.name}:** \`${enumDef.values.join(' | ')}\``);
        lines.push('');
      }
    }
  }

  // Global notes
  if (map.notes && map.notes.length > 0) {
    lines.push(`## ${s.notes}`);
    lines.push('');

    for (const note of map.notes) {
      lines.push(`- ${note}`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*This document was auto-generated by the Migration Prep tool.*');

  return lines.join('\n');
}
